terraform {
  required_version = ">= 1.6"
  required_providers {
    samsungcloudplatformv2 = {
      source  = "SamsungSDSCloud/samsungcloudplatformv2"
      version = ">= 0.0.1"
    }
  }
}

provider "samsungcloudplatformv2" {}

# Read-only data-source smoke fixture (generated by scripts/gen_ds_smoke.py).
# Creates NOTHING: each block exercises a list/read endpoint with no or
# constant-only arguments, so plan/apply verify the data-source code paths.

data "samsungcloudplatformv2_iam_access_keys" "smoke" {
}

data "samsungcloudplatformv2_iam_groups" "smoke" {
}

data "samsungcloudplatformv2_iam_policies" "smoke" {
}

data "samsungcloudplatformv2_iam_role" "smoke" {
}

data "samsungcloudplatformv2_iam_role_policy_bindings" "smoke" {
}

data "samsungcloudplatformv2_iam_roles" "smoke" {
}

data "samsungcloudplatformv2_iam_user" "smoke" {
}

data "samsungcloudplatformv2_iam_user_policy_bindings" "smoke" {
}

data "samsungcloudplatformv2_iam_users" "smoke" {
}
