terraform {
  required_version = ">= 1.6"
  required_providers {
    samsungcloudplatformv2 = {
      source  = "SamsungSDSCloud/samsungcloudplatformv2"
      version = ">= 0.0.1"
    }
  }
}

provider "samsungcloudplatformv2" {}

# Read-only data-source smoke fixture (generated by scripts/gen_ds_smoke.py).
# Creates NOTHING: each block exercises a list/read endpoint with no or
# constant-only arguments, so plan/apply verify the data-source code paths.

data "samsungcloudplatformv2_virtualserver_image" "smoke" {
}

data "samsungcloudplatformv2_virtualserver_images" "smoke" {
}

data "samsungcloudplatformv2_virtualserver_keypair" "smoke" {
}

data "samsungcloudplatformv2_virtualserver_keypairs" "smoke" {
}

data "samsungcloudplatformv2_virtualserver_server" "smoke" {
}

data "samsungcloudplatformv2_virtualserver_server_group" "smoke" {
}

data "samsungcloudplatformv2_virtualserver_server_groups" "smoke" {
}

data "samsungcloudplatformv2_virtualserver_servers" "smoke" {
}

data "samsungcloudplatformv2_virtualserver_volume" "smoke" {
}

data "samsungcloudplatformv2_virtualserver_volumes" "smoke" {
}
