terraform {
  required_version = ">= 1.6"
  required_providers {
    samsungcloudplatformv2 = {
      source  = "SamsungSDSCloud/samsungcloudplatformv2"
      version = ">= 0.0.1"
    }
  }
}

provider "samsungcloudplatformv2" {}

# Read-only data-source smoke fixture (generated by scripts/gen_ds_smoke.py).
# Creates NOTHING: each block exercises a list/read endpoint with no or
# constant-only arguments, so plan/apply verify the data-source code paths.

data "samsungcloudplatformv2_ske_clusters" "smoke" {
}

data "samsungcloudplatformv2_ske_kubernetes_versions" "smoke" {
}

data "samsungcloudplatformv2_ske_nodepool_images" "smoke" {
  scp_original_image_type = "k8s"
}
