terraform {
  required_version = ">= 1.6"
  required_providers {
    samsungcloudplatformv2 = {
      source  = "SamsungSDSCloud/samsungcloudplatformv2"
      version = ">= 0.0.1"
    }
  }
}

provider "samsungcloudplatformv2" {}

# Read-only data-source smoke fixture (generated by scripts/gen_ds_smoke.py).
# Creates NOTHING: each block exercises a list/read endpoint with no or
# constant-only arguments, so plan/apply verify the data-source code paths.

data "samsungcloudplatformv2_loadbalancer_lb_certificates" "smoke" {
}

data "samsungcloudplatformv2_loadbalancer_lb_health_checks" "smoke" {
}

data "samsungcloudplatformv2_loadbalancer_lb_listener" "smoke" {
}

data "samsungcloudplatformv2_loadbalancer_lb_listeners" "smoke" {
}

data "samsungcloudplatformv2_loadbalancer_lb_member" "smoke" {
}

data "samsungcloudplatformv2_loadbalancer_lb_members" "smoke" {
}

data "samsungcloudplatformv2_loadbalancer_lb_server_group" "smoke" {
}

data "samsungcloudplatformv2_loadbalancer_lb_server_groups" "smoke" {
}

data "samsungcloudplatformv2_loadbalancer_loadbalancer" "smoke" {
}

data "samsungcloudplatformv2_loadbalancer_loadbalancer_private_nat_ip" "smoke" {
}

data "samsungcloudplatformv2_loadbalancer_loadbalancers" "smoke" {
}
