#!/usr/bin/env python3
"""Render coverage/coverage.json into a self-contained GitHub Pages dashboard
(docs/index.html). Covers the FULL provider surface from
coverage/provider_surface.json (generated by scripts/gen_ds_smoke.py):
87 managed resources (capability funnel) plus 168 data sources (read-smoke
section), so the page shows the whole coverage picture.

Usage: python3 scripts/build_coverage_html.py
"""
import json
import os
import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COV = os.path.join(ROOT, "coverage", "coverage.json")
SURFACE = os.path.join(ROOT, "coverage", "provider_surface.json")
UNPROV = os.path.join(ROOT, "coverage", "excluded_resources.yaml")
OUT_DIR = os.path.join(ROOT, "docs")
OUT = os.path.join(OUT_DIR, "index.html")

PREFIX = "samsungcloudplatformv2_"
STAGE_ORDER = ["validate", "plan", "apply", "replan", "update", "import", "destroy"]
# cell color classes
CLS = {
    "ok": "ok", "fail": "fail", "skip": "skip", "blocked": "blocked",
    "unsupported": "unsup", "untested": "none", "excluded": "skip",
    "": "none", None: "none",
}


def load(path, default):
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return default


def load_unprov(path):
    """Curated excluded resources (license / no-capacity / deprecated).
    short name -> {reason, detail}. Missing/unparseable -> {}."""
    if not os.path.exists(path):
        return {}
    try:
        import yaml
        with open(path) as f:
            data = yaml.safe_load(f) or {}
        return {k: v for k, v in data.items() if isinstance(v, dict)}
    except Exception:
        return {}


def short(t):
    return t[len(PREFIX):] if t.startswith(PREFIX) else t


def ds_read_status(rec):
    """Read verdict for a smoke scenario record (reads happen at plan time)."""
    if not rec:
        return "untested"
    st = rec.get("stages") or {}
    if st.get("plan") == "ok":
        return "ok"
    if "fail" in (st.get("validate"), st.get("plan")):
        return "fail"
    if "blocked" in (st.get("validate"), st.get("plan"), st.get("apply")):
        return "blocked"
    return "untested"


def main():
    cov = load(COV, {})
    surface = load(SURFACE, {})
    unprov = load_unprov(UNPROV)
    resources = surface.get("resources", {})
    datasources = surface.get("datasources", {})

    def rec_of(short_type):
        return cov.get(PREFIX + short_type) or cov.get(short_type)

    # ---- resources ----
    all_res = set(resources)
    for k in cov:
        if not k.startswith("ds_"):
            all_res.add(short(k))
    surface_total = len(all_res)
    # Split out platform-unprovisionable resources (license / no-capacity): not
    # defects, excluded from the testable denominator, shown greyed in their
    # own section below.
    unprov_res = sorted(r for r in all_res if r in unprov)
    testable_res = [r for r in all_res if r not in unprov]
    total = len(testable_res)

    by_family = {}
    for r in sorted(testable_res):
        fam = (resources.get(r) or {}).get("family") or r.split("_", 1)[0]
        by_family.setdefault(fam, []).append(r)

    # which stages actually appear (so update/import only show if used)
    present_stages = set()
    for rec in cov.values():
        present_stages.update((rec.get("stages") or {}).keys())
    stages = [s for s in STAGE_ORDER if s in present_stages] or ["validate", "plan", "apply", "replan", "destroy"]
    CORE = ["validate", "plan", "apply", "replan", "destroy"]

    def stage_ok(rec, s):
        return (rec.get("stages") or {}).get(s) == "ok"

    res_recs = {r: rec_of(r) for r in testable_res}
    with_run = sum(1 for rec in res_recs.values() if rec)
    reach = {s: sum(1 for rec in res_recs.values() if rec and stage_ok(rec, s)) for s in CORE}
    green = sum(1 for rec in res_recs.values() if rec and all(stage_ok(rec, s) for s in CORE))

    # ---- data sources ----
    ds_status = {}
    for t, e in sorted(datasources.items()):
        if e.get("excluded"):
            ds_status[t] = ("excluded", e.get("reason", ""))
        else:
            rec = cov.get(e["scenario"])
            st = ds_read_status(rec)
            note = "via " + e["scenario"]
            if rec and st != "ok" and rec.get("note"):
                note += " — " + rec["note"]
            ds_status[t] = (st, note)
    ds_total = len(datasources)
    ds_smoke = sum(1 for e in datasources.values() if e.get("scenario"))
    ds_green = sum(1 for st, _ in ds_status.values() if st == "ok")
    ds_excl = ds_total - ds_smoke

    def pct(n):
        return f"{100.0*n/total:.1f}%" if total else "0%"

    gen = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    # ---- HTML: resource table ----
    rows = []
    for fam in sorted(by_family):
        res = by_family[fam]
        fam_green = sum(1 for r in res if res_recs[r] and all(stage_ok(res_recs[r], s) for s in CORE))
        rows.append(f'<tr class="fam"><td colspan="{2+len(stages)}">{fam} '
                    f'<span class="cnt">{fam_green} green / {sum(1 for r in res if res_recs[r])} run / {len(res)} total</span></td></tr>')
        for r in res:
            rec = res_recs[r]
            cells = []
            for s in stages:
                v = (rec.get("stages") or {}).get(s) if rec else None
                cls = CLS.get(v, "none")
                txt = v if v else "—"
                cells.append(f'<td class="cell {cls}" title="{s}: {txt}">{txt}</td>')
            if rec:
                note = (rec.get("note") or "").replace('"', "&quot;")[:300]
                run = rec.get("last_run_url") or ""
                seen = (rec.get("last_seen") or "")[:10]
                last = f'<a href="{run}" target="_blank">{seen}</a>' if run else seen
                name_html = f'<span title="{note}">{r}</span>' if note else r
            else:
                last = '<span class="muted">no run yet</span>'
                name_html = f'<span class="muted">{r}</span>'
            rows.append(f'<tr><td class="rname">{name_html}</td>' + "".join(cells) + f'<td class="last">{last}</td></tr>')

    # ---- HTML: data source table ----
    ds_by_family = {}
    for t, e in datasources.items():
        ds_by_family.setdefault(e["family"], []).append(t)
    ds_rows = []
    for fam in sorted(ds_by_family):
        members = sorted(ds_by_family[fam])
        fam_green = sum(1 for t in members if ds_status[t][0] == "ok")
        ds_rows.append(f'<tr class="fam"><td colspan="3">{fam} '
                       f'<span class="cnt">{fam_green} read-verified / {len(members)} total</span></td></tr>')
        for t in members:
            st, note = ds_status[t]
            note = (note or "").replace('"', "&quot;")
            cls = CLS.get(st, "none")
            ds_rows.append(f'<tr><td class="rname">{t}</td>'
                           f'<td class="cell {cls}">{st}</td>'
                           f'<td class="dsnote">{note[:160]}</td></tr>')

    # ---- HTML: unprovisionable table (greyed, separate) ----
    unprov_rows = []
    for r in unprov_res:
        meta = unprov.get(r, {})
        reason = meta.get("reason", "-")
        detail = (meta.get("detail") or "").replace('"', "&quot;").strip()
        fam = (resources.get(r) or {}).get("family") or r.split("_", 1)[0]
        unprov_rows.append(
            f'<tr class="unprovrow"><td class="rname">{r}</td>'
            f'<td>{fam}</td>'
            f'<td><span class="rtag {reason}">{reason}</span></td>'
            f'<td class="dsnote">{detail[:240]}</td></tr>'
        )

    head_cells = "".join(f"<th>{s}</th>" for s in stages)
    funnel = f"""
      <div class="cards">
        <div class="card"><div class="num">{total}</div><div class="lbl">managed resources</div></div>
        <div class="card"><div class="num">{with_run}</div><div class="lbl">have a matrix run<br><span class="muted">{pct(with_run)}</span></div></div>
        <div class="card"><div class="num">{reach['apply']}</div><div class="lbl">reach apply<br><span class="muted">{pct(reach['apply'])}</span></div></div>
        <div class="card green"><div class="num">{green}<span class="denom">/{total}</span></div><div class="lbl">fully GREEN<br><span class="muted">{pct(green)} of testable</span></div></div>
        <div class="card unprov"><div class="num">{len(unprov_res)}</div><div class="lbl">excluded<br><span class="muted">license / no-capacity / deprecated</span></div></div>
        <div class="card"><div class="num">{ds_green}<span class="denom">/{ds_smoke}</span></div>
          <div class="lbl">data sources read-verified<br><span class="muted">{ds_total} total · {ds_excl} excluded (need parent arg)</span></div></div>
      </div>
      <div class="bar">
        <span>validate {reach['validate']}</span><span>plan {reach['plan']}</span>
        <span>apply {reach['apply']}</span><span>replan {reach['replan']}</span><span>destroy {reach['destroy']}</span>
      </div>"""

    html = f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>SCP Terraform provider — coverage dashboard</title>
<style>
 :root{{--ok:#1a7f37;--fail:#cf222e;--skip:#6e7781;--unsup:#9a6700;--blocked:#bc4c00;--none:#eaeef2}}
 body{{font:14px/1.45 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0;color:#1f2328;background:#f6f8fa}}
 header{{background:#0d1117;color:#fff;padding:18px 24px}}
 header h1{{margin:0;font-size:18px}} header .sub{{color:#9aa4b2;font-size:12px;margin-top:4px}}
 main{{max-width:1100px;margin:0 auto;padding:20px}}
 h2{{font-size:16px;margin:26px 0 8px}}
 .cards{{display:flex;gap:12px;flex-wrap:wrap;margin:8px 0 4px}}
 .card{{flex:1;min-width:150px;background:#fff;border:1px solid #d0d7de;border-radius:10px;padding:14px 16px}}
 .card.green{{border-color:var(--ok);box-shadow:0 0 0 1px var(--ok) inset}}
 .card .num{{font-size:30px;font-weight:700}} .card .lbl{{color:#57606a;font-size:12px}}
 .card .denom{{font-size:16px;color:#8c959f;font-weight:400}}
 .muted{{color:#8c959f}}
 .bar{{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0 18px;font-size:12px;color:#57606a}}
 .bar span{{background:#fff;border:1px solid #d0d7de;border-radius:20px;padding:3px 10px}}
 table{{width:100%;border-collapse:collapse;background:#fff;border:1px solid #d0d7de;border-radius:10px;overflow:hidden}}
 th,td{{padding:6px 8px;text-align:left;border-bottom:1px solid #eaeef2;font-size:12.5px}}
 th{{background:#f6f8fa;position:sticky;top:0}}
 tr.fam td{{background:#eef2f6;font-weight:700;text-transform:capitalize}}
 tr.fam .cnt{{font-weight:400;color:#57606a;font-size:11px;margin-left:8px}}
 .rname{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}}
 td.cell{{text-align:center;font-weight:600;color:#fff;border-radius:4px}}
 .cell.ok{{background:var(--ok)}} .cell.fail{{background:var(--fail)}} .cell.skip{{background:var(--skip)}}
 .cell.unsup{{background:var(--unsup)}} .cell.blocked{{background:var(--blocked)}}
 .cell.none{{background:var(--none);color:#8c959f}}
 .dsnote{{color:#57606a;font-size:12px}}
 .card.unprov{{border-style:dashed;background:#f6f8fa}} .card.unprov .num{{color:#8c959f}}
 table.unprovtable tr.unprovrow td{{background:#f6f8fa;color:#6e7781}}
 table.unprovtable tr.unprovrow .rname{{color:#57606a}}
 .rtag{{display:inline-block;padding:1px 8px;border-radius:20px;font-size:11px;font-weight:600;color:#fff;background:var(--skip)}}
 .rtag.license{{background:#8250df}} .rtag.no-capacity{{background:#6e7781}} .rtag.deprecated{{background:#bc4c00}}
 .legend{{margin:14px 0;font-size:12px;color:#57606a;display:flex;gap:10px;flex-wrap:wrap}}
 .legend b{{display:inline-block;width:12px;height:12px;border-radius:3px;vertical-align:-2px;margin-right:4px}}
 a{{color:#0969da;text-decoration:none}} a:hover{{text-decoration:underline}}
 .last{{white-space:nowrap;font-size:11.5px}}
</style></head><body>
<header>
  <h1>SCP Terraform provider — capability coverage</h1>
  <div class="sub">Generated {gen} · source: capability matrix (issue #13) · stages: validate → plan → apply → replan → destroy (+ optional update/import) · data sources read-verified via ds_&lt;family&gt; smoke scenarios</div>
</header>
<main>
  {funnel}
  <div class="legend">
    <span><b style="background:var(--ok)"></b>ok</span>
    <span><b style="background:var(--fail)"></b>fail</span>
    <span><b style="background:var(--skip)"></b>skip / excluded</span>
    <span><b style="background:var(--unsup)"></b>unsupported (no import)</span>
    <span><b style="background:var(--blocked)"></b>blocked</span>
    <span><b style="background:var(--none)"></b>no run</span>
    <span class="muted">· hover a resource for the last error/note</span>
  </div>
  <h2 id="resources">Managed resources ({green}/{total} fully green)</h2>
  <table>
    <thead><tr><th>resource</th>{head_cells}<th>last run</th></tr></thead>
    <tbody>
      {''.join(rows)}
    </tbody>
  </table>
  <h2 id="excluded">Excluded resources — not in testable surface ({len(unprov_res)})</h2>
  <p class="muted" style="margin:4px 0 10px">Resources <b>excluded from the testable surface</b> (the funnel denominator) above — <b>not</b> provider/fixture defects.
  Reasons: a vendor <b>license</b> the account does not hold, physical hardware / entitlement / <b>capacity</b> the account lacks, or a <b>deprecated</b> service being retired.
  Split out the same way parent-arg-only data sources are, so "100% coverage" means 100% of what is actually testable. Curated in <code>coverage/excluded_resources.yaml</code>.</p>
  <table class="unprovtable">
    <thead><tr><th>resource</th><th>family</th><th>reason</th><th>why it cannot be provisioned</th></tr></thead>
    <tbody>
      {''.join(unprov_rows)}
    </tbody>
  </table>
  <h2 id="datasources">Data sources ({ds_green}/{ds_smoke} read-verified · {ds_excl} excluded)</h2>
  <p class="muted" style="margin:4px 0 10px">Read-only smoke: each <code>ds_&lt;family&gt;</code> scenario reads every standalone-readable
  data source of the family (list endpoints, optional/constant-only args); <b>ok</b> = the scenario's plan (which performs the reads) is green.
  <b>excluded</b> = requires a parent-resource argument, so it is only exercised implicitly by resource scenarios.</p>
  <table>
    <thead><tr><th>data source</th><th>read</th><th>note</th></tr></thead>
    <tbody>
      {''.join(ds_rows)}
    </tbody>
  </table>
  <p class="muted" style="margin-top:16px">Coverage store: <code>coverage/coverage.json</code> · surface: <code>coverage/provider_surface.json</code> · regenerate locally with
  <code>python3 scripts/build_coverage.py out/capability-matrix.json &amp;&amp; python3 scripts/build_coverage_html.py</code>.</p>
</main></body></html>"""

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT, "w") as f:
        f.write(html)
    print(f"wrote {OUT}: {total} resources ({green} green), {ds_total} datasources ({ds_green} read-verified, {ds_excl} excluded)")


if __name__ == "__main__":
    main()
